services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: hi
      POSTGRES_PASSWORD: hi
      POSTGRES_DB: hi
    ports:
      - "5442:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
